Support wagtail42
cfpb/wagtail-sharing pull request #61
Opened 2023-02-13 15:16 UTC by nickmoreton

This updates the package for Wagtail 4.2

## Additions

Wagtail 4.1

-

## Removals

Wagtail < 4.1

-

## Changes
-

## Testing

Updates github actions and tox matrix

-

## Review

- @user

[Preview this PR without the whitespace changes](?w=0)

## Screenshots

## Notes

-

## Todos

-

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

2023-02-13 15:19 UTC, nickmoreton commented on .github/workflows/test.yml
> +
Cancels previous running actions if not finished.

2023-02-13 15:22 UTC, nickmoreton commented on wagtailsharing/models.py
> +            page = self.get_latest_revision_as_object()
Changed in Wagtail 4.0

2023-02-13 15:22 UTC, nickmoreton commented on wagtailsharing/views.py
> +        page = page.get_latest_revision_as_object()
Changed in Wagtail 4.0

2023-02-16 15:52 UTC, victoriachan requested changes
Hi Nick, I have reviewed this. It looks good. The Readme needs updating though. I have attached some new screenshots to save you the trouble. 

I wasn't sure if the Page.serve() changes would affect this, so I tried this locally and it works fine.

2023-02-17 11:05 UTC, nickmoreton commented on README.rst
>  This project has been tested for compatibility with:
Thanks @victoriachan I have updated the docs.

And thanks so much for the screen shots too 👍

2023-02-27 10:48 UTC, victoriachan commented on README.rst
>  This project has been tested for compatibility with:
Looks good!

2023-02-27 10:49 UTC, victoriachan commented
Looks good to me!

2023-02-27 10:50 UTC, victoriachan approved these changes

2023-03-16 18:09 UTC, willbarton commented
@nickmoreton It looks like your upgrade commits are relatively independent of the token commits. I'll pull them into a separate branch and get it ready to merge!

2023-03-17 18:21 UTC, closed without merging